name: test
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: run tests
        run : go run main.go
  call-other:
    needs: test
    uses: mattkasun/test/.github/workflows/test.yml@master
    with:
      version: v0.20.1
      some_data: "hello world"
      some_bool: true
    secrets: inherit
    
